### PR TITLE
Adjustments to let it run on macOS Ventura+ and build on Gradle 8+

### PR DESCRIPTION
**Pull request by pskowronek**
Adjustments to let it run on macOS Ventura+ and build on Gradle 8+.

- added gradlew
- removed `JavaAppLauncher` and `JavaAppLauncherStub`
- using `universalJavaApplicationStub` always (Apple and Oracle app styles use `universalJavaApplicationStub`)
- adjusted plugin code to work with Gradle 8+
- adjusted `universalJavaApplicationStub` to properly parse paths and version on Vantura+ 
- contains fixes from #74

I know that author of this awesome plugin stopped maintaining this but maybe this PR will be approved.
Either it's going to be integrated in this repo, or I would need to publish it under a different id (or embed it into other projects code to use it).

### CODE REVIEW

**Comment by crotwell** [comment]
I have tried to test your PR using an old test case here, but after multiple attempts I keep hitting errors. They very likely may be due to my system or trying to publish the plugin locally to test, but get:
```
* What went wrong:
Could not determine the dependencies of task ':copyToResourcesJava'.
> Resolving dependency configuration 'default' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'default' should be resolved.
```

Have you been able to test successfully?

I am concerned that most of the code in this plugin is so old that it has subtle incompatibilities with newer ways of writing plugins for gradle. I am not opposed to upgrading and publishing it, but I am not developing java gui applications any more, so my ability to spend time on this is very limited.

If you would like to take it over and publish yourself under a new name, I would be happy to pass it on.

**Comment by pskowronek** [comment]
> I have tried to test your PR using an old test case here, but after multiple attempts I keep hitting errors. They very likely may be due to my system or trying to publish the plugin locally to test, but get:

Are you able to share that test case? (`canBeResolved` - as I have no clue so far).

> If you would like to take it over and publish yourself under a new name, I would be happy to pass it on.

I will think about it :/

**Comment by pskowronek** [comment]
I will try to take a look (gradle, their docs, their hermetic error reporting and the way they change things always give me a headache  :) )

**Comment by crotwell** [comment]
I feel your pain...
:(

**Comment by pskowronek** [comment]
Don't ask me why or what it does (I guess I'm not alone, but [this](https://youtrack.jetbrains.com/issue/IDEA-276365/Resolving-dependency-configuration-compileOnly-is-not-allowed-as-it-is-defined-as-canBeResolvedfalse.#focus=Comments-27-6691957.0-0) gave me that hint), add this to app/build.gradle (after plugins): `configurations.default.canBeResolved=true`

Then I added config for macAppBundle:
```
macAppBundle {                                                                                                                                                               
    appName = 'Test'                                                                                                                                                         
    mainClassName = 'org.example.App'                                                                                                                                        
    appStyle = 'universalJavaApplicationStub'                                                                                                                                
                                                                                                                                                                             
    bundleJRE = false                                                                                                                                                        
    javaProperties.put('apple.laf.useScreenMenuBar', 'true')                                                                                                                 
    appIconX = 50                                                                                                                                                            
    appIconY = 120                                                                                                                                                           
    appFolderX = 330                                                                                                                                                         
    appFolderY = 120                                                                                                                                                         
}
```

**Comment by crotwell** [comment]
Published...thanks for doing this.
https://plugins.gradle.org/plugin/edu.sc.seis.macAppBundle

**Comment by pskowronek** [comment]
Thanks!

**Pull request merged**
